// File generated by the FlutterFire CLI.
// For more information, please visit https://firebase.google.com/docs/flutter/setup
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl3NM09aQJPORl49l4blRJOn8QzAu-H8E',
    appId: '1:900631831881:web:550307fdcf6a3c9562e698',
    messagingSenderId: '900631831881',
    projectId: 'edutrack-49094',
    authDomain: 'edutrack-49094.firebaseapp.com',
    storageBucket: 'edutrack-49094.firebasestorage.app',
    measurementId: 'G-E3ZNGK3ETD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWM-06cy_jpsMfHHFGLAYJAq_tB9ASJU',
    appId: '1:900631831881:android:82198b8a0c65d3d562e698',
    messagingSenderId: '900631831881',
    projectId: 'edutrack-49094',
    storageBucket: 'edutrack-49094.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0wFsmkdpOrxiqDfW0xPQ1Wg8GoqLBjA',
    appId: '1:900631831881:ios:32197f04cef2b04462e698',
    messagingSenderId: '900631831881',
    projectId: 'edutrack-49094',
    storageBucket: 'edutrack-49094.firebasestorage.app',
    iosBundleId: 'com.example.edutrackDemo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0wFsmkdpOrxiqDfW0xPQ1Wg8GoqLBjA',
    appId: '1:900631831881:ios:32197f04cef2b04462e698',
    messagingSenderId: '900631831881',
    projectId: 'edutrack-49094',
    storageBucket: 'edutrack-49094.firebasestorage.app',
    iosBundleId: 'com.example.edutrackDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7f7fOVKQjmKm1W23HfkUjBj1tdPxoc0Q',
    appId: '1:900631831881:web:588593cb5100c06562e698',
    messagingSenderId: '900631831881',
    projectId: 'edutrack-49094',
    authDomain: 'edutrack-49094.firebaseapp.com',
    storageBucket: 'edutrack-49094.firebasestorage.app',
    measurementId: 'G-JP3V4F97N2',
  );

}